@startuml c4_component
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(api, "Backend API", "Node.js/Express", "REST API com JWT")

System_Boundary(system, "Sistema de Descarte Inteligente") {
    left to right direction
    ' Componentes de Login
    package "Componentes de Usuário" {
        Component(signInServer, "Componente de login", "Componente: Controller/UserController.js", "Gerencia login")
        Component(signUp, "Componente de cadastro", "Componente: controllers/userController.js", "Gerencia cadastro")
        Component(authController, "Controle de autenticação", "Gerencia login, JWT")
        Component(userProfileService, "Componente de perfil de usuário", "Componente: Controller/UserController.js", "Gerencia perfil de usuário")
    }

    ' Componentes de Tarefas
    package "Componentes de Tarefas" {
        Component(taskService, "Componente de tarefas de descarte", "Componenente: Controller/taskController.js", "Gerencia tarefas de descarte")
    }

    ' Componentes de Lembretes (comentados por enquanto)
    package "Componentes de Lembretes" {
        Component(suggestionService, "Componente de Lembretes", "Consulta API externa para categorias")
    }

    ' Componentes de Localização (comentados por enquanto)
    package "Componentes de Localização" {
        Component(locationService, "Componente de localização", "Localiza pontos de coleta")
    }

    ' Componentes de Histórico (comentados por enquanto)
    package "Componentes de Histórico" {
        Component(historyService, "Componente de Histórico", "Gerencia histórico e boas práticas")
    }
}

ContainerDb(db, "Banco de Dados", "PostgreSQL, Supabase", "Armazena perfis, tarefas, histórico")
system -up-> api : "Chama a API [JSON/HTTPS]"

' Componente de cadastro
signUp -down-> authController : "Valida os dados"

' Componente de login
signInServer -down-> authController : "Valida os dados"

authController -down-> db : "Escreve dados do usuário no banco de dados"

' Gerenciamanto de perfil chama cadastro para editar dados
userProfileService -> db : "Lê dados do usuário"
userProfileService -down-> signUp : "Chama componente de cadastro"

' Registrar tarefas de descarte (ex: "levar eletrônico ao ponto de coleta").
taskService --> db : "CRUD"


@enduml
